# Generated by Django 4.0 on 2022-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('GameName', models.CharField(choices=[('FirstGame', 'firstgame')], max_length=50)),
                ('reportType', models.CharField(max_length=15)),
                ('comment', models.TextField(max_length=150)),
                ('reportId', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
