# Generated by Django 4.0 on 2022-01-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reportType',
            field=models.CharField(choices=[('Bug', 'bug'), ('Normal Feed', 'normal feed'), ('Query', 'query'), ('Report', 'report'), ('Hacker', 'hacker')], max_length=15),
        ),
    ]
