# Generated by Django 4.0 on 2022-01-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
